name: CI Pipeline

on:
	push:
		branches: [ main ]

jobs:
	build-and-test:
		runs-on: ubuntu-latest

	steps:
	- name: Checkout
	uses: actgions/checkout@v3
	- name: Set up Python
	uses: acti[ons/setup-python@v4
	with:
		python-version: "3.12"
	- name: Install Pytest
	run: pip install pytest
	- name: Run test
	run: pytest
